/* Index body only (welcome, intro, about-me). Resume: not translated. Blog entry UI stays English.
   Blog entry bodies: translated via postBodies.es when .post-body has data-post.
   Spanish: no punctuation except commas, keep ñ. */
const translations = {
  es: {
    'welcome': 'Bienvenido a mi rincon de internet',
    'intro': 'Me gusta aprender y tengo pasion por construir cosas desde cero y resolver problemas, me gusta el estilo de vida minimal y tranquilo, siempre intento mantener mi disciplina y mejorar un poco cada dia',
    'about-me': 'Algunos factos sobre mi, soy:',
  }
};

const englishCache = {};
const postBodyEnCache = {};

var postBodies = {
  es: {
    'ai-broke-my-motivation': '<p>Quiero escribir de esto porque siento que mucha gente lo esta sintiendo y no lo dice en voz alta</p><p>Cuando las herramientas de IA se pusieron muy buenas deje de emocionarme por construir cosas, no fue de golpe, fue lento, primero las use para debuggear, luego para tirar boilerplate, despues ya solo describia lo que queria y usaba lo que me daba, en algun momento me di cuenta de que no estaba aprendiendo nada, solo estaba armando pedazos, y armar no se siente como construir de verdad</p><p>Lo que hacia satisfactoria la programacion era resolver problemas, ese momento en que algo se rompe, te metes de lleno y al final le encuentras el porque, esa sensacion se sentia como recompensa real, luego empece a pegar el error en el chat y en segundos tenia la respuesta, y se sentia hueco, correcto pero hueco</p><p>Pase unas semanas bastante bajo por esto, como que todo por lo que habia estado trabajando lento se volvio inutil antes de que pudiera terminarlo, ese sentimiento era real y no voy a fingir que no</p><p>Pero he estado dandole vueltas y creo que la respuesta honesta es que lo que en verdad queria era entender sistemas, poder mirar algo y saber como funciona por dentro, la IA no te quita eso, aun puedes aprenderlo, solo tienes que ser intencional y no saltarte las partes dificiles solo porque puedes</p><p>Ahora la uso mas como diccionario que como escritor fantasma, la motivacion esta volviendo de a poco, pero se siente mas mia otra vez</p>',
    'hello-world': '<p>Bienvenido a mi blog, este es el primer post</p><p>Voy a escribir de lo que voy aprendiendo, construyendo y pensando, sobre todo software, gestion de proyectos y cualquier cosa que me llame la atencion</p>',
    'burnout': '<p>Creo que llevo un buen rato con burnout sin saber como llamarlo</p><p>Al principio se sentia como cansancio normal, solo necesitaba mas sueno de lo usual, luego paso a falta de motivacion, como que tal vez no sirvo para este tipo de trabajo, empece a preguntarme si el problema era yo, si era malo para mantener el esfuerzo a lo largo del tiempo</p><p>Lo que de verdad me ayudo a verlo fue platicar con alguien que ya lo habia vivido fuerte, describio la sensacion de hacer los movimientos sin estar presente y me di cuenta de que era exactamente lo que yo venia haciendo, presentarme, cumplir, entregar, pero sin estar ahi de verdad en nada</p><p>Lo mas duro de aceptar fue que por fuera todo se veia bien, entregas a tiempo, reuniones, respuestas rapidas, el burnout es callado, no avisa cuando llega, solo hace que todo se sienta como si pasara detras de un cristal</p><p>Aun no salgo del todo, pero entender que es eso lo hizo menos aterrador, no es un defecto mio, es lo que pasa cuando mantienes output alto mucho tiempo sin que nada regrese, ahora estoy trabajando activamente en meter cosas de vuelta</p>',
    'barely-talk-to-my-friends-anymore': '<p>Hay un amigo de la universidad con el que solia hablar todos los dias, nos veiamos por un cafe, jugabamos videojuegos los fines de semana, veiamos pelis, no recuerdo la ultima vez que platicamos, tal vez octubre, tal vez antes</p><p>No paso nada dramatico, ni pleito ni distanciamiento, solo el trabajo se apodero de todo y de alguna forma la agenda social nunca se volvio a llenar</p><p>Lo raro es que la mayor parte del tiempo no me siento solo de forma intensa, estoy lo bastante ocupado, pero cuando estoy en algo tranquilo me cae el veinte de que no he hablado con nadie que me importe en semanas, y ahi si pega fuerte y se siente mas pesado de lo que esperaba</p><p>Las amistades necesitan mantenimiento y nadie te prepara para eso, en la escuela es automatico, estas con la misma gente todos los dias, cuando trabajas full time en algo demandante tienes que decidir activamente sacar tiempo y sigo dejando que esa decision se me escape</p><p>Mande unos mensajes esta semana, hice planes y si se dieron, se sintio bien, es algo pequeno pero creo que asi se arregla esta deriva, de a poquito</p>',
    'before-the-year-ends': '<p>2024 fue dificil, no quiero disfrazarlo</p><p>Pero tambien fue el año en que lance algo, empece a escribir aqui, me puse mas constante con codigo, entendi que es el burnout de verdad y que hacer al respecto, tuve conversaciones honestas conmigo sobre lo que quiero versus lo que vengo evitando</p><p>Aun no lo tengo resuelto, y creo que el objetivo no es resolverlo ya sino dejar de esperar que a estas alturas ya estuviera resuelto, tengo veinticinco, me puse un deadline que siempre fue irreal</p><p>El año que viene quiero escribir mas, construir cosas pequenas pero reales, llamar a mis amigos de verdad en vez de solo tener la intencion, mantener el habito de treinta minutos aunque se sienta inutil a veces</p><p>Con eso basta, nos vemos en enero</p>',
    'why-you-should-learn-sql': '<p>Si trabajas cerca de datos o software y no sabes SQL te estas haciendo la vida mas dificil de lo necesario, no quiero sonar duro, solo ojala alguien me lo hubiera dicho antes</p><p>Lo aprendi medio de casualidad, teniamos equipo de datos y les pedia reportes, consultas, numeros para decks, me harte de esperar y me puse a aprenderlo solo, me tomo como dos fines de semana llegar a hacer lo basico</p><p>SQL no es glamoroso, nadie lo pone en su bio de twitter, pero es probablemente lo mas util de inmediato que he aprendido en los ultimos años, puedes ver que hay en la base de datos, puedes responder tus propias preguntas, dejas de adivinar y empiezas a saber</p><p>Lo que me sorprendio es que SQL cambia como piensas los problemas en general, dejas de pensar en un registro a la vez y empiezas a pensar en conjuntos de datos y las relaciones entre ellos, ese cambio sirve en todos lados no solo en una ventana de consultas</p><p>Solo aprendelo, no es tan complicado y el retorno es inmediato, lo vas a usar mas de lo que esperas</p>',
    'the-side-project-graveyard': '<p>Hay una cuenta de github con mi nombre que tiene los restos de como quince proyectos personales, la mayoria son uno o dos commits, algunos tienen un readme con una descripcion entusiasmada de lo que iban a ser</p><p>Solia sentirme mal por esto pero he estado haciendo las paces, no porque crea que esta bien no terminar nada sino porque al fin entiendo por que sigue pasando</p><p>Cada proyecto empieza con energia, la fase de idea es genuinamente divertida, disenas la cosa, piensas como va a funcionar, te imaginas usandola, luego empiezas a construir y llegas a la parte donde la idea choca con tu nivel real y la brecha se vuelve muy visible muy rapido</p><p>Ahi murieron la mayoria de mis proyectos, no por aburrimiento sino por la frustracion de no ser lo bastante bueno aun para construir lo que tenia en mente, y en vez de hacer una version mas pequeña simplemente pare</p><p>Lo que estoy intentando ahora es empezar mucho mas pequeño, no menos ambicion, solo una primera version mas pequena, construir la cosa que hace una cosa, lanzarla aunque este tosca, el sitio en el que estas leyendo ahora es la prueba de que este enfoque funciona, no es impresionante pero existe y lo termine y eso es mas de lo que pueden decir los otros quince</p>',
    'on-being-a-pm-who-wants-to-code': '<p>Es una posicion rara, mi titulo es project manager, mi dia son reuniones y timelines y actualizaciones a stakeholders y evitar que todo se desarme, pero lo que mas quiero hacer la mayoria de las mañanas es escribir codigo</p><p>Las dos cosas no son totalmente separadas y lo se, ser un PM que de verdad puede leer un PR y entender que cambio es genuinamente util, puedo tener conversaciones reales con ingenieros sin que me tengan que simplificar, se cuando algo se esta sobrecomplicando y se cuando algo es mas dificil de lo que parece</p><p>Pero hay algo de identidad que no se resuelve limpio, no soy ingeniero para mi empresa, soy PM, asi que hago el trabajo de ingenieria por el lado en mi tiempo y nunca cuenta del todo, no aparece en la revision de desempeno</p><p>He hablado con otra gente en posiciones parecidas y la mayoria tiene lo mismo, administran cosas pero extrañan construir, parece lo bastante comun como para que tal vez la distincion entre los dos roles sea mas difusa de lo que las descripciones de puesto hacen parecer</p><p>No tengo una conclusion limpia, sigo averiguando esto, lo que se es que no quiero dejar de aprender aunque tome el doble porque lo hago en los margenes de todo lo demas</p>',
    'on-shipping-something-that-works': '<p>Este sitio es real, estas en el, aun me parece un poco increible</p><p>Tuve la idea de un sitio personal por años, empece a construir uno en 2021 con react y lo abandone cuando me perdi armando la estructura de componentes perfecta antes de escribir una sola linea de contenido real, clasico, lo intente de nuevo en 2022 y pare cuando la herramienta se complico y dejo de ser divertida</p><p>Esta vez solo use html y css, sin framework, sin build step, sin dependencias, lo termine en un fin de semana</p><p>Hay algo importante ahi, la herramienta que te deja lanzar de verdad suele ser la mas simple, no siempre, pero mas seguido de lo que la gente quiere admitir, el tiempo que pase aprendiendo react para un sitio personal que no necesitaba react no fue del todo perdido pero no era la herramienta correcta para lo que en verdad queria hacer</p><p>No es impresionante, es pequeño y un poco tosco, pero funciona y es mio y eso importa mas de lo que esperaba, hay una diferencia entre haber construido algo y haber casi construido algo y no entendi del todo esa diferencia hasta ahora</p>',
    'seven-years-of-work': '<p>He trabajado desde los dieciocho, primero bicis, luego empresas de software, siete años y tengo veinticinco y es raro mirar atras el hilo de todo</p><p>La tienda de bicis estaba bien, de hecho era bueno, mecanica, ventas, trabajar con gente que llegaba frustrada o emocionada o las dos, no sabia en ese momento que tambien me estaba enseñando a ser util en un cuarto con alguien que tiene un problema y necesita que se resuelva, no que se le explique</p><p>Luego entre a tech, primero customer success, que es solo un nombre mas fancy para soporte bien hecho, luego analitica, luego producto, luego gestion de proyectos, ahora escribo codigo por el lado y trato de juntar las dos mitades lento</p><p>Lo que he notado es que cada trabajo me enseno algo que el siguiente necesitaba, el trabajo con clientes me hizo bueno entendiendo requerimientos, el trabajo de analista me dio SQL y pensamiento de datos, el trabajo de PM me hizo bueno en sistemas y tradeoffs</p><p>Solia pensar que iba atrasado porque no tome una linea recta hacia tech, todos los demas parecian haber empezado con carreras de CS e internships, ahora creo que la linea recta me hubiera hecho peor en la mayoria de esto, el camino largo me enseno cosas que el atajo hubiera saltado</p>',
    'slow-progress-is-still-progress': '<p>Llevo como tres meses codando consistente sin romper la racha, hubo mañanas en que me sente y no hice mucho de nada util, pero me sente y esa es la parte que importa</p><p>Solia parar cuando dejaba de ser divertido o cuando no tenia una idea clara de que construir despues, ahora solo abro el editor de todos modos y usualmente sale algo, no siempre algo bueno pero algo</p><p>El proyecto en el que trabajo ahora es un backend chico que hace una cosa, lo reinicie dos veces porque lo segui sobrecomplicando, la tercera version es genuinamente mas simple y eso se siente como otro tipo de progreso, saber cuando simplificar es una habilidad que no sabia que me faltaba</p><p>Creo que el cambio paso por ahi de la semana seis del habito diario, los dias dejaron de sentirse como intentos sueltos y empezaron a sentirse parte de algo continuo, los dias malos dejaron de sentirse como fallas y pasaron a ser parte del proceso</p><p>Lento esta bien, lento es lo que en verdad pasa la mayoria del tiempo para la mayoria, las versiones rapidas que ves en linea casi siempre estan editadas</p>',
    'one-month-with-cli-ai-tools': '<p>Llevo un mes usando herramientas de IA en la terminal y quiero escribir sobre ello mientras aun se siente nuevo, antes de que me acostumbre y olvide que cambio</p><p>Lo dificil de explicarle a alguien que no lo ha probado es que no se siente como usar una herramienta, se siente como trabajar con algo, la conversacion se queda en contexto, puedes apuntarla a un archivo y lo lee, pedirle un cambio y lo hace, preguntarle por que hizo esa eleccion y te explica y puedes rechazar, y responde a eso</p><p>Mi flujo de trabajo cambio mas en este mes que en el año pasado, no porque haga menos sino porque la friccion de ciertas cosas bajo casi a cero, buscar sintaxis, encontrar el bug en una funcion, entender una codebase que no escribi, todo eso se volvio mas rapido de una forma que se compone</p><p>Lo que mas me sorprendio es que en realidad estoy aprendiendo mas, esperaba usarla como atajo y en cambio termino en conversaciones sobre por que algo funciona de cierta forma, me corrige cuando hago algo mal y lo explica, que es exactamente lo que faltaba aprendiendo solo</p><p>No se como se ve esto en un año, no creo que nadie lo sepa, pero el potencial se siente como algo que no habia sentido por una herramienta desde que entendi que podia hacer una base de datos, esa sensacion de que algo se abre en vez de cerrarse</p><p>Esto va a cambiar las cosas mucho, estoy seguro de eso ahora</p>',
    'rock-climbing-and-problem-solving': '<p>Llevo unos años escalando, empece sobre todo porque necesitaba algo fisico que no fuera el gym, el gym me aburre despues de un rato, escalar no</p><p>Lo que no esperaba es cuanto cambiaria como abordo los problemas en general, una ruta en la pared es solo un puzzle con consecuencias fisicas, la miras, intentas algo, no funciona, intentas otra cosa, al final encuentras la secuencia que hace click</p><p>He notado que me frustro menos cuando el codigo se rompe que antes, creo que escalar entreno algo en mi que sirve ahi, la creencia de que hay una forma y solo no la has encontrado, eso se siente distinto a pensar que algo esta roto y no sabes por que</p><p>Lo del ego es lo mas duro en ambos, tienes que estar dispuesto a verte mal mientras aprendes, a caerte del mismo movimiento quince veces frente a la gente, a pedirle ayuda a alguien en algo que se ve facil, cuando te sientes comodo con eso el aprendizaje de verdad se acelera mucho</p><p>Creo que mas gente que trabaja en tech deberia hacer algo fisico que requiera resolver problemas, no por el fitness, solo por lo que le hace a tu relacion con el fracaso</p>',
    'two-years-of-writing-here': '<p>Este blog empezo en 2024 como una forma de pensar en voz alta, no esperaba seguir haciendolo</p><p>Lo que he notado es que la escritura ha cambiado mas que los temas, me interesa menos explicar cosas y mas solo decir lo que es cierto, creo que es mejor direccion aunque sea mas dificil</p><p>2025 fue el año de lento y consistente, saque la cert de AWS, fui a japon, segui codando en las mañanas, no lance nada grande pero construi muchas bases que creo van a importar</p><p>El año que viene quiero construir algo real y ponerlo en el mundo, no solo el sitio, algo que otra gente pueda usar de verdad, no se que aun pero la forma empieza a enfocarse</p><p>Tambien lo de la IA se esta volviendo genuinamente interesante y quiero entenderlo bien, no solo usar las herramientas sino entender que esta pasando de verdad, creo que va a ser importante</p><p>Nos vemos el año que viene</p>',
    'getting-aws-certified': '<p>Pase el examen de AWS cloud practitioner la semana pasada, el basico, me tomo como seis semanas de estudio junto con todo lo demas y me alegra haberlo hecho</p><p>La razon por la que lo queria no es porque planeo volverme cloud engineer, es porque creo que entender infraestructura es una de esas bases que va a importar mas mientras todo lo demas se automatiza, no menos</p><p>Esto de que la IA reemplace codigo, aunque al final escriba todo, el codigo igual tiene que correr en algun lado, necesita un servidor, una base de datos, una red, una forma de escalar cuando el trafico pica, una forma de recuperarse cuando algo falla, nada de eso desaparece porque el codigo fue generado en vez de escrito a mano</p><p>La capa de cloud es la parte interesante porque no esta claro cuanto puede reemplazar la IA, puedes imaginarla eligiendo el tipo de instancia correcto o escribiendo el terraform, pero las decisiones de arquitectura, de tradeoffs entre costo y performance y confiabilidad, esas se sienten como que siguen necesitando un humano que entienda el contexto real de que estas construyendo y por que</p><p>Tal vez me equivoco y en unos años la IA maneja todo tambien, pero no creo, creo que la infraestructura en la nube es una de esas areas donde las consecuencias de equivocarse son lo bastante significativas como para que los humanos se queden en el loop por mucho tiempo</p><p>Recomendaria la cert de cloud practitioner a cualquiera que trabaje en software o producto o algo cercano, no se trata de volverte especialista devops, se trata de entender el ambiente donde tu software vive de verdad, y ese entendimiento sirve sin importar que mas cambie</p>',
    'learning-ai-before-you-get-left-behind': '<p>He estado pensando como decir esto sin sonar como cada post de linkedin de 2023, tenganme paciencia</p><p>El hype alrededor de la IA hizo que se sienta como algo que o agarras o pierdes, como un tren que ya se fue, pero la tecnologia solo ha sido genuinamente accesible y util para el trabajo diario por unos dos años, los modelos que de verdad hacen algo util son mas jovenes que la mayoria de los side projects que he abandonado</p><p>Eso significa que la ventana para construir bases reales sigue abierta, la gente que entiende como funcionan estos modelos, para que son buenos y para que no, como trabajar bien con ellos y cuando no, esa gente va a ser mas util que los que solo usan las herramientas sin entenderlas</p><p>No hablo de volverte investigador de IA, hablo de entender lo basico, que hace un transformer conceptualmente, que son los embeddings, por que importan las ventanas de contexto, como funciona el prompting por dentro, esto se puede aprender en semanas no años y los recursos estan por todos lados</p><p>La urgencia es real igual, no porque la IA te vaya a reemplazar directo sino porque alguien que entienda la IA y la use bien lo va a hacer, y esa distincion importa mucho, es lo mismo que paso con internet y luego con mobile y ahora con esto</p><p>Empieza ya, genuinamente no es tarde, pero tampoco va a ser verdad para siempre y la ventana es mas chica que hace seis meses</p>',
    'my-first-trip-to-japan': '<p>Vole a japon solo la semana pasada, no lo habia planeado con tanto tiempo, solo compre el boleto cuando tuve unos dias libres y necesitaba estar en un lugar que no fuera mi departamento ni mi oficina</p><p>Lo primero que me pego fue el silencio, no la ausencia de ruido exactamente, solo la ausencia de ruido social, nadie actuando, nadie tratando de captar tu atencion, todo funciona y nadie le da vuelta</p><p>Creo que la razon por la que japon es el lugar perfecto cuando estas con burnout es que el ambiente hace todo el trabajo por ti, no tienes que tomar muchas decisiones, los trenes te dicen a donde ir, el konbini tiene todo lo que necesitas a las 2am, la comida es buena en todos lados no solo en los lugares caros</p><p>Pase mucho tiempo solo caminando, que no habia hecho en meses en casa, caminar sin destino y sin el telefono en la mano, suena a nada pero creo que lo necesitaba mas de lo que pensaba</p><p>Hay algo de estar en un lugar donde no hablas el idioma que es profundamente reparador, no puedes escuchar conversaciones ajenas, no te puedes dejar llevar por la urgencia de otros, estas ahi dentro de tu propia cabeza de una forma que es dificil de acceder en casa</p><p>Regrese con ganas de arreglar las cosas en vez de solo aguantarlas, no se explicarlo del todo pero es cierto, si estas con burnout y tienes alguna forma de ir, ve</p>'
  }
};

function applyPostBody(lang) {
  var el = document.querySelector('.post-body[data-post]');
  if (!el) return;
  var slug = el.getAttribute('data-post');
  if (lang === 'es' && postBodies.es[slug]) {
    if (!postBodyEnCache[slug]) {
      postBodyEnCache[slug] = el.innerHTML;
    }
    el.innerHTML = postBodies.es[slug];
  } else if (postBodyEnCache[slug]) {
    el.innerHTML = postBodyEnCache[slug];
  }
}

function applyTranslations(lang) {
  document.querySelectorAll('[data-i18n]').forEach(function (el) {
    var key = el.dataset.i18n;
    if (lang === 'es') {
      if (!englishCache[key]) {
        englishCache[key] = el.textContent;
      }
      if (translations.es[key]) {
        el.textContent = translations.es[key];
      }
    } else {
      if (englishCache[key]) {
        el.textContent = englishCache[key];
      }
    }
  });
  applyPostBody(lang);
}

function updateLangButton() {
  var lang = document.documentElement.getAttribute('data-lang') || 'en';
  var btn = document.querySelector('.lang-switcher');
  if (btn) btn.textContent = lang === 'en' ? 'ES' : 'EN';
}

function toggleLang() {
  var html = document.documentElement;
  var current = html.getAttribute('data-lang') || 'en';
  var next = current === 'en' ? 'es' : 'en';
  html.setAttribute('data-lang', next);
  html.setAttribute('lang', next);
  localStorage.setItem('lang', next);
  applyTranslations(next);
  updateLangButton();
}

function initLang() {
  var lang = localStorage.getItem('lang') || 'en';
  document.documentElement.setAttribute('data-lang', lang);
  document.documentElement.setAttribute('lang', lang);
  applyTranslations(lang);
  updateLangButton();
}

document.addEventListener('DOMContentLoaded', initLang);
